apiVersion: v1
kind: Service
metadata:
  name: omni-query-ui
  namespace: omni-query
spec:
  selector:
    app: omni-query-ui
  ports:
    - port: {{ .Values.service.ui.port }}
      targetPort: 8501
  type: {{ .Values.service.ui.type }}
