"""
Image chunking per PRD Layer 2.

Each image patch is one chunk — no splitting.
The chunk's text content for BM25 / reranking = Gemini description + caption.
Both the text representation (for BM25 and reranker) and raw image bytes
(for Gemini Embedding 2 visual embedding) are stored per chunk.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class ImageChunk:
    """A single image chunk with both text and visual representations."""

    text_content: str       # description + caption (for BM25 + reranker)
    image_bytes: bytes      # raw JPEG (for Gemini Embedding 2 visual embed)
    doc_name: str
    page_id: int
    layout_id: int
    img_path: str
    quote_id: str = ""
    chunk_type: str = "image"
    modality: str = "image"
    parent_chunk_id: str = ""
    token_count: int = 0


class ImageChunker:
    """
    Converts image patches + descriptions into ImageChunks.

    Accepts both MMDocRAG img_quote records (with pre-computed descriptions)
    and raw ImagePatch objects from PyMuPDF extraction.
    """

    def chunk_from_img_quote(self, img_quote: dict, image_bytes: bytes,
                              doc_name: str) -> ImageChunk:
        """
        Build an ImageChunk from an MMDocRAG img_quote record.
        Uses the pre-computed img_description from the dataset where available.
        """
        description = img_quote.get("img_description", "")
        caption = img_quote.get("caption", "")
        text_content = f"{description}\n{caption}".strip()

        return ImageChunk(
            text_content=text_content,
            image_bytes=image_bytes,
            doc_name=doc_name,
            page_id=img_quote["page_id"],
            layout_id=img_quote["layout_id"],
            img_path=img_quote["img_path"],
            quote_id=img_quote["quote_id"],
            token_count=len(text_content.split()),
            parent_chunk_id=f"{doc_name}_{img_quote['layout_id']}_image",
        )

    def chunk_from_patch(self, image_bytes: bytes, page_id: int, layout_id: int,
                          doc_name: str, description: str = "", caption: str = "",
                          img_path: str = "") -> ImageChunk:
        """
        Build an ImageChunk from a raw PyMuPDF-extracted image patch.
        Description must be pre-generated by ImageDescriber.
        """
        text_content = f"{description}\n{caption}".strip()
        return ImageChunk(
            text_content=text_content,
            image_bytes=image_bytes,
            doc_name=doc_name,
            page_id=page_id,
            layout_id=layout_id,
            img_path=img_path,
            token_count=len(text_content.split()),
            parent_chunk_id=f"{doc_name}_{layout_id}_image",
        )
